import { Product } from './types';

export const CURATED_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Chikankari Hand-Embroidered White Kurti',
    brand: 'Anouk',
    description: 'A gorgeous white cotton straight kurti featuring intricate hand-embroidered Lucknowi Chikankari work on the neck, sleeves, and hem. Unbelievably soft, airy, and perfect for summers.',
    url: 'https://www.myntra.com/kurtis/anouk/anouk-women-chikankari-embroidered-kurti/10294821',
    category: 'Kurtis',
    tags: ['White Kurti', 'Chikankari', 'Cotton', 'Lucknowi', 'Summer Wear'],
    price: 1299,
    originalPrice: 2499,
    rating: 4.6,
    reviewCount: 1240,
    image: '', // Unverified exact image - fallback to elegant placeholder as requested
    platform: 'Myntra',
    featured: true,
    dateAdded: '2026-05-12',
    accentColor: '#EC4899'
  },
  {
    id: 'p2',
    title: 'Pure Cotton A-Line White Kurti',
    brand: 'Sangria',
    description: 'Casual regular wear A-line solid white kurti with wooden button detailing and a smart mandarin collar. Includes two functional side pockets.',
    url: 'https://www.ajio.com/sangria-a-line-cotton-kurti-white/p/460921832',
    category: 'Kurtis',
    tags: ['White Kurti', 'A-Line', 'Casual', 'Pure Cotton', 'Mandarin Collar'],
    price: 699,
    originalPrice: 1499,
    rating: 4.2,
    reviewCount: 890,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-01',
    accentColor: '#0D9488'
  },
  {
    id: 'p3',
    title: 'Anarkali Georgette White Kurti with Dupatta',
    brand: 'BIBA',
    description: 'An elegant pristine white Anarkali kurti made of premium georgette fabric. Complemented with a gorgeous golden zari embroidered borders and matching chiffon dupatta.',
    url: 'https://www.amazon.in/BIBA-Womens-Anarkali-Salwar-White/dp/B09V7C8R2Y',
    category: 'Anarkali',
    tags: ['White Kurti', 'Anarkali', 'Party Wear', 'Georgette', 'Embroidery'],
    price: 3499,
    originalPrice: 5999,
    rating: 4.8,
    reviewCount: 312,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Amazon',
    featured: true,
    dateAdded: '2026-04-18',
    accentColor: '#F59E0B'
  },
  {
    id: 'p4',
    title: 'Indigo Blue Block Print Kurta Set',
    brand: 'Libas',
    description: 'Beautiful Jaipur block printed straight cotton kurta with matching slim pants and an organic mulmul dupatta. Elegant contrast border detailing.',
    url: 'https://www.myntra.com/kurta-sets/libas/libas-women-indigo-printed-kurta-set/12839218',
    category: 'Kurta Sets',
    tags: ['Indigo Blue', 'Block Print', 'Jaipur', 'Kurta Set', 'Linen-Cotton'],
    price: 1899,
    originalPrice: 3999,
    rating: 4.5,
    reviewCount: 2150,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Myntra',
    featured: true,
    dateAdded: '2026-03-25',
    accentColor: '#EC4899'
  },
  {
    id: 'p5',
    title: 'Short White Cotton Tunic Top',
    brand: 'Fabindia',
    description: 'Handcrafted short white cotton kurti/tunic with stylish pintuck details on the chest. Perfect pair for blue denims or trousers.',
    url: 'https://www.nykaafashion.com/fabindia-white-cotton-pintuck-tunic/p/879124',
    category: 'Tunic Tops',
    tags: ['White Kurti', 'Short Tunic', 'Pintuck', 'Handcrafted', 'Office Wear'],
    price: 1199,
    originalPrice: 1599,
    rating: 4.4,
    reviewCount: 450,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Nykaa Fashion',
    featured: false,
    dateAdded: '2026-05-20',
    accentColor: '#DB2777'
  },
  {
    id: 'p6',
    title: 'Sage Green Pastel Cotton Kurta Set',
    brand: 'W for Woman',
    description: 'A soothing pastel sage green straight-cut cotton-blend kurta paired with matching floral printed palazzos and block printed borders.',
    url: 'https://www.ajio.com/w-sage-green-cotton-kurta-set/p/461908234',
    category: 'Kurta Sets',
    tags: ['Sage Green', 'Pastel', 'Kurta Set', 'Comfort Fit', 'Dailywear'],
    price: 1599,
    originalPrice: 2999,
    rating: 4.3,
    reviewCount: 670,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Ajio',
    featured: true,
    dateAdded: '2026-02-15',
    accentColor: '#0D9488'
  },
  {
    id: 'p7',
    title: 'Handcrafted Cotton Ikat Ethnic Dress',
    brand: 'Fabindia',
    description: 'Traditional Pochampally Ikat woven knee-length flare dress with smart wooden buttons and round neck. Sustainable pure cotton fabric.',
    url: 'https://www.myntra.com/dresses/fabindia/fabindia-ikat-handcrafted-dress/11928372',
    category: 'Ethnic Dresses',
    tags: ['Ikat Woven', 'Handcrafted', 'Pochampally', 'Flare Dress', 'Sustainable'],
    price: 2499,
    originalPrice: 3499,
    rating: 4.7,
    reviewCount: 180,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-01-30',
    accentColor: '#EC4899'
  },
  {
    id: 'p8',
    title: 'Gold-Printed White Anarkali Kurta',
    brand: 'Aurelia',
    description: 'Dazzling white festive Anarkali with metallic gold foil print patterns all over the flare. Stylish keyhole neck and rich 3/4th sleeves.',
    url: 'https://www.flipkart.com/aurelia-women-gold-printed-white-anarkali-kurta/p/itm1293817',
    category: 'Anarkali',
    tags: ['White Kurti', 'Anarkali', 'Gold Print', 'Festive Wear', 'Foil Print'],
    price: 1399,
    originalPrice: 2799,
    rating: 4.1,
    reviewCount: 1100,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Flipkart',
    featured: false,
    dateAdded: '2026-05-02',
    accentColor: '#2563EB'
  },
  {
    id: 'p9',
    title: 'Handblock Printed Ethnic Tiered Dress',
    brand: 'Sangria',
    description: 'Vibrant three-tier floral dress with adjustable waist tassels. Soft cotton cambric with a fluid sweep for styling versatility.',
    url: 'https://www.myntra.com/dresses/sangria/sangria-handblock-tiered-dress/13928172',
    category: 'Ethnic Dresses',
    tags: ['Handblock', 'Floral', 'Tiered Dress', 'Tassels', 'Boho Ethnic'],
    price: 1199,
    originalPrice: 2499,
    rating: 4.4,
    reviewCount: 930,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-04-10',
    accentColor: '#EC4899'
  },
  {
    id: 'p10',
    title: 'Floral Embroidered Georgette White Kurti',
    brand: 'House of Chikankari',
    description: 'A premium semi-sheer white georgette kurti showcasing elegant white-on-white shadow embroidery work. Light-weight and matches beautifully with white palazzos.',
    url: 'https://www.nykaafashion.com/house-of-chikankari-white-georgette-embroidered-kurti/p/3829104',
    category: 'Kurtis',
    tags: ['White Kurti', 'Georgette', 'Floral Embroidery', 'House of Chikankari', 'Semi-Sheer'],
    price: 2650,
    originalPrice: 3200,
    rating: 4.9,
    reviewCount: 154,
    image: '', // Unverified exact image - fallback to placeholder
    platform: 'Nykaa Fashion',
    featured: true,
    dateAdded: '2026-06-18',
    accentColor: '#DB2777'
  },
  {
    id: 'p11',
    title: 'Women Pink Printed Kurta Set',
    brand: 'Libas',
    description: 'Beautiful pink and white keyhole neck straight kurta set with floral block printing. Made of breathable cotton with standard straight pants.',
    url: 'https://www.myntra.com/kurta-sets/libas/libas-women-pink-floral-kurta-set/13829104',
    category: 'Kurta Sets',
    tags: ['Pink Kurta', 'Floral Print', 'Kurta Set', 'Cotton', 'Summer Outfits'],
    price: 1499,
    originalPrice: 2999,
    rating: 4.3,
    reviewCount: 620,
    image: '',
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-04-15',
    accentColor: '#EC4899'
  },
  {
    id: 'p12',
    title: 'Floral Print Straight Kurta',
    brand: 'Aurelia',
    description: 'Casual multi-colored floral printed regular fit straight kurta with a smart round neck and comfortable three-quarter sleeves.',
    url: 'https://www.amazon.in/Aurelia-Womens-Floral-Straight-Kurta/dp/B09C34821D',
    category: 'Kurtis',
    tags: ['Floral Kurti', 'Straight Kurta', 'Casual Wear', 'Rayon', 'Office Wear'],
    price: 799,
    originalPrice: 1599,
    rating: 4.0,
    reviewCount: 540,
    image: '',
    platform: 'Amazon',
    featured: false,
    dateAdded: '2026-05-18',
    accentColor: '#F59E0B'
  },
  {
    id: 'p13',
    title: 'Women Red Cotton Kurta Set',
    brand: 'BIBA',
    description: 'Festive red cotton straight-cut ethnic kurta paired with matching floral printed palazzos and a solid dyed red chiffon dupatta.',
    url: 'https://www.flipkart.com/biba-women-red-cotton-kurta-set/p/itm4829104',
    category: 'Kurta Sets',
    tags: ['Red Kurta', 'Cotton', 'Kurta Set', 'Festive Wear', 'Palazzos'],
    price: 2499,
    originalPrice: 4999,
    rating: 4.5,
    reviewCount: 280,
    image: '',
    platform: 'Flipkart',
    featured: false,
    dateAdded: '2026-03-12',
    accentColor: '#2563EB'
  },
  {
    id: 'p14',
    title: 'Solid Blue Tunic Top',
    brand: 'W for Woman',
    description: 'An elegant indigo blue solid tunic top with a mandarin collar, short button-up placket, and functional side pockets. Pairs perfectly with denim.',
    url: 'https://www.ajio.com/w-solid-blue-tunic-top/p/461928374',
    category: 'Tunic Tops',
    tags: ['Blue Tunic', 'Solid Tunic', 'Mandarin Collar', 'Pockets', 'Dailywear'],
    price: 999,
    originalPrice: 1799,
    rating: 4.1,
    reviewCount: 310,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-05',
    accentColor: '#0D9488'
  },
  {
    id: 'p15',
    title: 'Yellow Block Print Ethnic Dress',
    brand: 'Sangria',
    description: 'Bright sunshine yellow block printed flare ethnic dress. Crafted from lightweight cambric cotton with adjustable drawstring tassels at the waist.',
    url: 'https://www.myntra.com/dresses/sangria/sangria-yellow-block-print-dress/14928104',
    category: 'Ethnic Dresses',
    tags: ['Yellow Dress', 'Block Print', 'Cotton', 'Flare Dress', 'Boho Casual'],
    price: 1099,
    originalPrice: 2299,
    rating: 4.4,
    reviewCount: 710,
    image: '',
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-05-22',
    accentColor: '#EC4899'
  },
  {
    id: 'p16',
    title: 'Block Printed A-Line Kurti',
    brand: 'Anouk',
    description: 'Elegant beige and brown handcrafted block printed A-line kurti with classy wooden buttons on the front placket.',
    url: 'https://www.ajio.com/anouk-block-printed-aline-kurti/p/462910482',
    category: 'Kurtis',
    tags: ['Block Print', 'A-Line', 'Beige Kurti', 'Cotton', 'Handicraft'],
    price: 899,
    originalPrice: 1999,
    rating: 4.2,
    reviewCount: 460,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-12',
    accentColor: '#0D9488'
  },
  {
    id: 'p17',
    title: 'Embroidered Chanderi Kurta Set',
    brand: 'Libas',
    description: 'A premium pink Chanderi silk embroidered straight kurta set with metallic zari borders, matching trousers, and an organza dupatta.',
    url: 'https://www.nykaafashion.com/libas-pink-embroidered-chanderi-kurta-set/p/928104',
    category: 'Kurta Sets',
    tags: ['Chanderi Silk', 'Kurta Set', 'Embroidery', 'Party Wear', 'Zari Border'],
    price: 3299,
    originalPrice: 6599,
    rating: 4.7,
    reviewCount: 190,
    image: '',
    platform: 'Nykaa Fashion',
    featured: true,
    dateAdded: '2026-04-20',
    accentColor: '#DB2777'
  },
  {
    id: 'p18',
    title: 'Black Georgette Chikankari Kurti',
    brand: 'House of Chikankari',
    description: 'A breathtaking midnight black semi-sheer georgette kurti with premium hand-done Chikankari shadow work embroidery. A festive stunner.',
    url: 'https://www.myntra.com/kurtis/house-of-chikankari/house-of-chikankari-black-kurti/14289104',
    category: 'Kurtis',
    tags: ['Black Kurti', 'Chikankari', 'Georgette', 'Party Wear', 'Handcrafted'],
    price: 2950,
    originalPrice: 3800,
    rating: 4.9,
    reviewCount: 380,
    image: '',
    platform: 'Myntra',
    featured: true,
    dateAdded: '2026-05-30',
    accentColor: '#EC4899'
  },
  {
    id: 'p19',
    title: 'Indigo Blue Dabu Print Kurta',
    brand: 'Fabindia',
    description: 'Classic handcrafted organic dabu mud-resist block printed straight cotton kurta. Beautifully dyed in natural indigo.',
    url: 'https://www.amazon.in/Fabindia-Indigo-Dabu-Print-Kurta/dp/B09D48291D',
    category: 'Kurtis',
    tags: ['Indigo Blue', 'Dabu Print', 'Natural Dye', 'Cotton', 'Handcrafted'],
    price: 1699,
    originalPrice: 2499,
    rating: 4.6,
    reviewCount: 220,
    image: '',
    platform: 'Amazon',
    featured: false,
    dateAdded: '2026-02-18',
    accentColor: '#F59E0B'
  },
  {
    id: 'p20',
    title: 'Green Rayon Straight Kurti',
    brand: 'Aurelia',
    description: 'Soothing mint green straight solid daily wear kurti with three-quarter length sleeves and elegant lace detailing on cuffs.',
    url: 'https://www.ajio.com/aurelia-green-rayon-straight-kurti/p/463810492',
    category: 'Kurtis',
    tags: ['Green Kurti', 'Rayon', 'Daily Wear', 'Lace Border', 'Casual Wear'],
    price: 599,
    originalPrice: 1199,
    rating: 4.1,
    reviewCount: 520,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-20',
    accentColor: '#0D9488'
  },
  {
    id: 'p21',
    title: 'Multicolored Cotton Kurta Set',
    brand: 'Sangria',
    description: 'Boho-chic multicolored patchwork print pure cotton straight kurta paired with matching beige cigarette pants and light chiffon dupatta.',
    url: 'https://www.flipkart.com/sangria-multicolored-cotton-kurta-set/p/itm4928104',
    category: 'Kurta Sets',
    tags: ['Kurta Set', 'Patchwork Print', 'Boho Chic', 'Cotton', 'Pants'],
    price: 1399,
    originalPrice: 2999,
    rating: 4.2,
    reviewCount: 390,
    image: '',
    platform: 'Flipkart',
    featured: false,
    dateAdded: '2026-04-12',
    accentColor: '#2563EB'
  },
  {
    id: 'p22',
    title: 'Peach Floral Anarkali',
    brand: 'W for Woman',
    description: 'Lovely pastel peach floor-length Anarkali kurta featuring rich dynamic floral designs, golden foil details, and comfortable cotton lining.',
    url: 'https://www.myntra.com/kurtis/w-for-woman/w-peach-floral-anarkali/15289104',
    category: 'Anarkali',
    tags: ['Peach Anarkali', 'Floral Print', 'Foil Details', 'Festive Wear', 'Cotton Lining'],
    price: 2199,
    originalPrice: 4299,
    rating: 4.4,
    reviewCount: 410,
    image: '',
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-05-15',
    accentColor: '#EC4899'
  },
  {
    id: 'p23',
    title: 'Women Blue Georgette Kurta Set',
    brand: 'BIBA',
    description: 'Elegant royal blue georgette solid straight kurta set accompanied with zari embroidered dupatta and straight pants.',
    url: 'https://www.nykaafashion.com/biba-blue-georgette-kurta-set/p/938491',
    category: 'Kurta Sets',
    tags: ['Royal Blue', 'Georgette', 'Kurta Set', 'Zari Work', 'Elegant'],
    price: 3899,
    originalPrice: 6999,
    rating: 4.8,
    reviewCount: 140,
    image: '',
    platform: 'Nykaa Fashion',
    featured: true,
    dateAdded: '2026-03-05',
    accentColor: '#DB2777'
  },
  {
    id: 'p24',
    title: 'Mustard Yellow Silk Blend Kurta Set',
    brand: 'Libas',
    description: 'Premium silk blend rich mustard yellow festive straight kurta set with traditional hand embroidery on the yoke and stylish matching brocade dupatta.',
    url: 'https://www.amazon.in/Libas-Mustard-Yellow-Brocade-Dupatta/dp/B09E48291E',
    category: 'Kurta Sets',
    tags: ['Mustard Yellow', 'Silk Blend', 'Festive Wear', 'Hand Embroidery', 'Brocade'],
    price: 2899,
    originalPrice: 5499,
    rating: 4.6,
    reviewCount: 310,
    image: '',
    platform: 'Amazon',
    featured: true,
    dateAdded: '2026-04-28',
    accentColor: '#F59E0B'
  },
  {
    id: 'p25',
    title: 'Maroon Hand-Printed Cotton Tunic',
    brand: 'Fabindia',
    description: 'Artisanal hand-printed rich maroon short cotton tunic top featuring deep round neck and smart bell-style flared sleeves.',
    url: 'https://www.ajio.com/fabindia-maroon-hand-printed-tunic/p/464810482',
    category: 'Tunic Tops',
    tags: ['Maroon Tunic', 'Short Tunic', 'Handmade', 'Flared Sleeves', 'Office Wear'],
    price: 1299,
    originalPrice: 1899,
    rating: 4.3,
    reviewCount: 180,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-15',
    accentColor: '#0D9488'
  },
  {
    id: 'p26',
    title: 'Olive Green Cotton Ethnic Dress',
    brand: 'Anouk',
    description: 'Classic olive green tier flared cotton dress featuring an adjustable ethnic belt with intricate tribal coin ornaments.',
    url: 'https://www.flipkart.com/anouk-olive-green-cotton-dress/p/itm5928104',
    category: 'Ethnic Dresses',
    tags: ['Olive Green', 'Cotton Dress', 'Tiered Dress', 'Tribal Belt', 'Boho'],
    price: 1199,
    originalPrice: 2499,
    rating: 4.2,
    reviewCount: 290,
    image: '',
    platform: 'Flipkart',
    featured: false,
    dateAdded: '2026-05-08',
    accentColor: '#2563EB'
  },
  {
    id: 'p27',
    title: 'Lilac Cotton Chikankari Kurti',
    brand: 'House of Chikankari',
    description: 'Stunning light pastel lilac pure cotton kurti highlighting Lucknowi handcrafted chikankari floral jaal work. Exceptionally breathable.',
    url: 'https://www.myntra.com/kurtis/house-of-chikankari/house-of-chikankari-lilac-cotton-kurti/15891048',
    category: 'Kurtis',
    tags: ['Lilac Kurti', 'Chikankari', 'Cotton', 'Pastel Outfits', ' Lucknowi'],
    price: 2450,
    originalPrice: 2990,
    rating: 4.8,
    reviewCount: 170,
    image: '',
    platform: 'Myntra',
    featured: false,
    dateAdded: '2026-06-10',
    accentColor: '#EC4899'
  },
  {
    id: 'p28',
    title: 'Rust Orange Solid Tunic Top',
    brand: 'Sangria',
    description: 'A minimal rust orange solid short tunic top in rayon fabric. Comfortable regular-fit style with premium pintuck layout on front.',
    url: 'https://www.ajio.com/sangria-rust-orange-tunic/p/465810423',
    category: 'Tunic Tops',
    tags: ['Orange Tunic', 'Rayon', 'Pintuck', 'Casual wear', 'Solid Tunics'],
    price: 649,
    originalPrice: 1299,
    rating: 4.0,
    reviewCount: 150,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-25',
    accentColor: '#0D9488'
  },
  {
    id: 'p29',
    title: 'Teal Blue Embroidered Kurta Set',
    brand: 'Aurelia',
    description: 'Stunning deep teal blue festive straight cut kurta set decorated with heavy gold embroidery work on the round neck. Accompanied with narrow pants.',
    url: 'https://www.nykaafashion.com/aurelia-teal-embroidered-kurta-set/p/948291',
    category: 'Kurta Sets',
    tags: ['Teal Blue', 'Embroidered', 'Festive Outfits', 'Gold Thread', 'Pants'],
    price: 1999,
    originalPrice: 3999,
    rating: 4.5,
    reviewCount: 330,
    image: '',
    platform: 'Nykaa Fashion',
    featured: false,
    dateAdded: '2026-04-02',
    accentColor: '#DB2777'
  },
  {
    id: 'p30',
    title: 'Beige Cotton Linen Straight Kurti',
    brand: 'BIBA',
    description: 'A classy minimalist linen blend beige kurti. Ideal for workspaces and warm weather. Features comfortable dual-sided pockets.',
    url: 'https://www.amazon.in/BIBA-Beige-Cotton-Linen-Kurti/dp/B09F48291F',
    category: 'Kurtis',
    tags: ['Beige Kurti', 'Linen Blend', 'Minimalist', 'Office Wear', 'Pockets'],
    price: 1399,
    originalPrice: 2499,
    rating: 4.4,
    reviewCount: 260,
    image: '',
    platform: 'Amazon',
    featured: false,
    dateAdded: '2026-05-05',
    accentColor: '#F59E0B'
  },
  {
    id: 'p31',
    title: 'Mustard Cotton Kurta Set',
    brand: 'W for Woman',
    description: 'Sophisticated festive mustard yellow printed straight cotton kurta with printed palazzos. Soft, comfortable, and perfect for morning events.',
    url: 'https://www.flipkart.com/w-women-mustard-printed-kurta-set/p/itm6928104',
    category: 'Kurta Sets',
    tags: ['Mustard Kurta', 'Cotton', 'Kurta Set', 'Printed Palazzos', 'Daywear'],
    price: 1699,
    originalPrice: 3299,
    rating: 4.3,
    reviewCount: 420,
    image: '',
    platform: 'Flipkart',
    featured: false,
    dateAdded: '2026-03-18',
    accentColor: '#2563EB'
  },
  {
    id: 'p32',
    title: 'Teal Floral Printed Ethnic Dress',
    brand: 'Libas',
    description: 'Full flair deep teal floral print flared cotton ethnic dress with smart flared sleeves and round keyhole neck pattern.',
    url: 'https://www.myntra.com/dresses/libas-teal-floral-ethnic-dress/16289104',
    category: 'Ethnic Dresses',
    tags: ['Teal Dress', 'Floral Print', 'Cotton', 'Keyhole Neck', 'Flare Dress'],
    price: 1499,
    originalPrice: 2999,
    rating: 4.6,
    reviewCount: 510,
    image: '',
    platform: 'Myntra',
    featured: true,
    dateAdded: '2026-04-10',
    accentColor: '#EC4899'
  },
  {
    id: 'p33',
    title: 'Block Printed Black Tunic Top',
    brand: 'Fabindia',
    description: 'An artisan-crafted block-printed black short tunic in breathable linen-cotton. Complemented with smart red-and-white print details on sleeves.',
    url: 'https://www.ajio.com/fabindia-black-printed-tunic/p/466810482',
    category: 'Tunic Tops',
    tags: ['Black Tunic', 'Linen-Cotton', 'Block Print', 'Handmade', 'Smart Casual'],
    price: 1399,
    originalPrice: 1999,
    rating: 4.5,
    reviewCount: 130,
    image: '',
    platform: 'Ajio',
    featured: false,
    dateAdded: '2026-06-28',
    accentColor: '#0D9488'
  },
  {
    id: 'p34',
    title: 'Handloom Cotton Straight Kurti',
    brand: 'Anouk',
    description: 'A gorgeous dark olive handloom pure cotton straight kurti featuring elegant self-stripe pattern weaves and standard slits on sides.',
    url: 'https://www.nykaafashion.com/anouk-olive-handloom-kurti/p/958291',
    category: 'Kurtis',
    tags: ['Olive Kurti', 'Handloom Cotton', 'Self Stripes', 'Traditional', 'Slits'],
    price: 999,
    originalPrice: 1999,
    rating: 4.1,
    reviewCount: 200,
    image: '',
    platform: 'Nykaa Fashion',
    featured: false,
    dateAdded: '2026-05-10',
    accentColor: '#DB2777'
  },
  {
    id: 'p35',
    title: 'Lemon Yellow Cotton Kurta',
    brand: 'House of Chikankari',
    description: 'Vibrant and bright pastel lemon yellow straight cotton kurti featuring elegant lucknowi chikankari embroidery on the front panel and hem.',
    url: 'https://www.amazon.in/House-of-Chikankari-Yellow-Cotton-Kurta/dp/B09G48291G',
    category: 'Kurtis',
    tags: ['Yellow Kurti', 'Chikankari', 'Cotton', 'Summer Outfits', 'Lucknowi Work'],
    price: 2250,
    originalPrice: 2800,
    rating: 4.8,
    reviewCount: 160,
    image: '',
    platform: 'Amazon',
    featured: false,
    dateAdded: '2026-06-02',
    accentColor: '#F59E0B'
  }
];

export const ALL_TAGS = Array.from(
  new Set(CURATED_PRODUCTS.flatMap(p => p.tags))
).sort();
